plugins:
  - jest
env:
  es2021: true
  node: true
extends:
  - 'airbnb-base'
  - 'plugin:jest/recommended'
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  no-console: 0
  import/extensions: 'off'
  no-prototype-builtins: 'off'
