name: my-app
version: 1.1.0
description: A simple application with additional features

services:
  web:
    image: nginx
    ports:
      - 80:80
  app:
    image: my-app
    ports:
      - 8080:8080
    environment:
      - FOO=bar
      - NEW_VAR=baz
  database:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data:
    driver: local
    size: 100G
