name: my-app
version: 1.0.0
description: A simple application

services:
  web:
    image: nginx
    ports:
      - 80:80
  app:
    image: my-app
    ports:
      - 8080:8080
    environment:
      - FOO=bar

volumes:
  data:
    driver: local
